function FileData_Pairs(x)
{
x.t("home","page");
x.t("working","protexpress");
x.t("protexpress","home");
x.t("protexpress","getting");
x.t("protexpress","enter");
x.t("resetting","password");
x.t("getting","started");
x.t("link","resetting");
x.t("registering","users");
x.t("account","registering");
x.t("forgot","password");
x.t("logging","working");
x.t("logging","logging");
x.t("logging","log");
x.t("started","logging");
x.t("enter","username");
x.t("click","forgot");
x.t("username","password");
x.t("page","account");
x.t("information","resetting");
x.t("users","forgotten");
x.t("password","protexpress");
x.t("password","link");
x.t("password","click");
x.t("password","information");
x.t("forgotten","password");
x.t("log","protexpress");
}
