function FileData_Pairs(x)
{
x.t("example","contact");
x.t("contact","system");
x.t("required","reset");
x.t("don\u2019t","remember");
x.t("working","protexpress");
x.t("protexpress","don\u2019t");
x.t("protexpress","getting");
x.t("reset","password");
x.t("resetting","password");
x.t("getting","started");
x.t("e-mail","address");
x.t("remember","username");
x.t("specified","registered");
x.t("address","required");
x.t("address","ones");
x.t("address","click");
x.t("started","resetting");
x.t("request","username");
x.t("ones","specified");
x.t("registered","protexpress");
x.t("forget","password");
x.t("enter","username");
x.t("click","submit");
x.t("username","example");
x.t("username","e-mail");
x.t("submit","request");
x.t("system","administrator");
x.t("password","working");
x.t("password","resetting");
x.t("password","forget");
x.t("password","enter");
x.t("password","username");
}
