function FileData_Pairs(x)
{
x.t("protocols","new");
x.t("protocols","review");
x.t("create","new");
x.t("working","protexpress");
x.t("protexpress","creating");
x.t("identify","experiment");
x.t("new","existing");
x.t("new","experiment");
x.t("add","new");
x.t("creating","new");
x.t("review","experiment");
x.t("first","identify");
x.t("identifying","experiment");
x.t("existing","protocols");
x.t("saving","information");
x.t("experiment","create");
x.t("experiment","working");
x.t("experiment","add");
x.t("experiment","creating");
x.t("experiment","first");
x.t("experiment","saving");
x.t("experiment","reviewing");
x.t("experiment","adding");
x.t("information","identifying");
x.t("reviewing","experiment");
x.t("adding","protocols");
}
