function FileData_Pairs(x)
{
x.t("protocols","managing");
x.t("managing","protocols");
x.t("managing","experiments");
x.t("experiments","importing");
x.t("working","protexpress");
x.t("protexpress","working");
x.t("protexpress","section");
x.t("getting","started");
x.t("includes","following");
x.t("started","managing");
x.t("importing","data");
x.t("section","includes");
x.t("exporting","experiment");
x.t("experiment","data");
x.t("data","exporting");
x.t("topics","getting");
x.t("following","topics");
}
