function FileData_Pairs(x)
{
x.t("confirming","successful");
x.t("protocols","deleting");
x.t("managing","protocols");
x.t("deleting","protocol");
x.t("working","protexpress");
x.t("protexpress","managing");
x.t("delete","search");
x.t("delete","click");
x.t("delete","protocol");
x.t("want","delete");
x.t("results","page");
x.t("search","results");
x.t("search","feature");
x.t("search","protocol");
x.t("feature","delete");
x.t("appears","confirming");
x.t("appears","row");
x.t("protexpress\u2019s","search");
x.t("row","corresponding");
x.t("message","appears");
x.t("click","message");
x.t("page","appears");
x.t("successful","deleting");
x.t("protocol","deleting");
x.t("protocol","working");
x.t("protocol","delete");
x.t("protocol","want");
x.t("protocol","search");
x.t("protocol","protexpress\u2019s");
x.t("corresponding","protocol");
}
