function FileData_Pairs(x)
{
x.t("protocols","experiment");
x.t("working","protexpress");
x.t("protexpress","creating");
x.t("new","experiment");
x.t("new","protocol");
x.t("creating","new");
x.t("section","contains");
x.t("existing","protocol");
x.t("experiment","working");
x.t("experiment","section");
x.t("experiment","adding");
x.t("topics","adding");
x.t("protocol","experiment");
x.t("following","topics");
x.t("adding","protocols");
x.t("adding","new");
x.t("adding","existing");
x.t("contains","following");
}
