function FileData_Pairs(x)
{
x.t("available","protocols");
x.t("protocols","protexpress");
x.t("deleting","input");
x.t("working","protexpress");
x.t("working","inputs");
x.t("protexpress","complete");
x.t("protexpress","creating");
x.t("editing","input");
x.t("new","experiment");
x.t("complete","protocol");
x.t("requires","least");
x.t("creating","new");
x.t("input","deleting");
x.t("input","editing");
x.t("input","section");
x.t("section","contains");
x.t("material","inputs");
x.t("least","input");
x.t("experiment","working");
x.t("data","material");
x.t("protocol","requires");
x.t("topics","adding");
x.t("following","topics");
x.t("adding","input");
x.t("inputs","available");
x.t("inputs","working");
x.t("inputs","specify");
x.t("specify","data");
x.t("contains","following");
}
