function FileData_Pairs(x)
{
x.t("available","protocols");
x.t("protocols","protexpress");
x.t("deleting","input");
x.t("working","protexpress");
x.t("necessary","complete");
x.t("protexpress","creating");
x.t("protexpress","section");
x.t("editing","input");
x.t("details","working");
x.t("details","editing");
x.t("details","complete");
x.t("new","experiment");
x.t("single","protocol");
x.t("complete","experiment");
x.t("complete","protocol");
x.t("add","single");
x.t("creating","new");
x.t("input","deleting");
x.t("input","details");
x.t("input","output");
x.t("section","contains");
x.t("material","inputs");
x.t("least","input");
x.t("experiment","editing");
x.t("experiment","data");
x.t("output","complete");
x.t("data","material");
x.t("protocol","available");
x.t("protocol","necessary");
x.t("protocol","contains");
x.t("topics","editing");
x.t("following","topics");
x.t("contains","least");
x.t("contains","following");
x.t("inputs","add");
}
