function FileData_Pairs(x)
{
x.t("properties","protexpress");
x.t("properties","experiment");
x.t("owner","edit");
x.t("working","protexpress");
x.t("working","experiment");
x.t("protexpress","editing");
x.t("protexpress","mirror");
x.t("editing","experiment");
x.t("editing","protocol");
x.t("details","editing");
x.t("details","adding");
x.t("mirror","specified");
x.t("specified","xar");
x.t("edit","experiment\u2019s");
x.t("experiment\u2019s","properties");
x.t("cpas","section");
x.t("format","used");
x.t("section","contains");
x.t("existing","experiment");
x.t("xar","format");
x.t("experiment","properties");
x.t("experiment","owner");
x.t("experiment","working");
x.t("experiment","editing");
x.t("experiment","details");
x.t("experiment","runs");
x.t("experiment","experiment");
x.t("experiment","run");
x.t("topics","editing");
x.t("protocol","details");
x.t("protocol","existing");
x.t("used","cpas");
x.t("following","topics");
x.t("run","working");
x.t("adding","protocol");
x.t("contains","following");
}
