function FileData_Pairs(x)
{
x.t("protocols","editing");
x.t("properties","edit");
x.t("managing","protocols");
x.t("owner","edit");
x.t("protexpress","managing");
x.t("editing","protocol");
x.t("true","webworks_writedivopen");
x.t("true","webworks_writedivclose");
x.t("edit","properties");
x.t("edit","protocol");
x.t("webworks_writedivopen","wwdd1071414");
x.t("webworksrootpath","wwdd1071414");
x.t("wwdd1071414","true");
x.t("webworks_writearrow","webworksrootpath");
x.t("protocol","owner");
x.t("protocol","editing");
x.t("protocol","webworks_writearrow");
x.t("protocol","protocol");
x.t("protocol","using");
x.t("using","protexpress");
}
