function  WWHBookData_AddTOCEntries(P)
{
var A=P.fN("Welcome to protExpress Online Help","0");
var B=A.fN("Using protExpress Online Help","1");
A=P.fN("Working with protExpress","2");
B=A.fN("Getting Started","3");
var C=B.fN("Registering Users","4");
C=B.fN("Logging In","5");
C=B.fN("Using the Home Page","6");
B=A.fN("Searching protExpress","7");
B=A.fN("Creating a New Experiment","8");
C=B.fN("Identifying the Experiment","9");
C=B.fN("Adding Protocols to an Experiment","10");
C=B.fN("Reviewing the Experiment","11");
C=B.fN("Managing Protocols","12");
var D=C.fN("Adding a Protocol","13");
D=C.fN("Editing a Protocol","14");
D=C.fN("Deleting a Protocol","15");
C=B.fN("Managing Experiments","16");
D=C.fN("Working with Experiments","17");
var E=D.fN("Adding an Experiment","18");
E=D.fN("Editing an Experiment","19");
E=D.fN("Deleting an Experiment","20");
D=C.fN("Applying Protocols to Experiments","21");
E=D.fN("Adding a Protocol Application","22");
E=D.fN("Deleting a Protocol Application","23");
D=C.fN("Working with Global Inputs","24");
E=D.fN("Adding a Global Input","25");
E=D.fN("Editing a Global Input","26");
E=D.fN("Deleting a Global Input","27");
D=C.fN("Working with Experiment Runs","28");
E=D.fN("Adding an Experiment Run","29");
E=D.fN("Editing an Experiment Run","30");
E=D.fN("Deleting an Experiment Run","31");
B=A.fN("Importing Data","32");
B=A.fN("Exporting Experiment Data","33");
A=P.fN("protExpress Glossary","34");
A=P.fN("Using Application Support","35");
}
