insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '1 experiment', '1 Test', '1 hypothesis 1', 'http://www.url1.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '2 Experiment 2', '2 TEST', '2 hypothesis 2', 'http://www.url2.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '3 ExpPERment 3', '3 Test', '3 hypothesis 3', 'http://www.url3.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '4 experiment 2', '4 Test', '4 hypothesis 1', 'http://www.url1.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '5 Experiment 2', '5 TEST', '5 hypothesis 2', 'http://www.url2.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '6 ExpPERment 3', '6 Test', '6 hypothesis 3', 'http://www.url3.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '7 experiment 3', '7 Test', '7 hypothesis 1', 'http://www.url1.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '8 Experiment 2', '8 TEST', '8 hypothesis 2', 'http://www.url2.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '9 ExpPERment 3', '9 Test', '9 hypothesis 3', 'http://www.url3.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '10 experiment 5', '10 Test', '10 hypothesis 1', 'http://www.url1.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '11 Experiment 2', '11 TEST', '11 hypothesis 2', 'http://www.url2.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '12 ExpPERment 3', '12 Test', '12 hypothesis 3', 'http://www.url3.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '13 experiment 2', '13 Test', '13 hypothesis 1', 'http://www.url1.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '14 Experiment 2', '14 TEST', '14 hypothesis 2', 'http://www.url2.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '15 ExpPERment 3', '15 Test', '15 hypothesis 3', 'http://www.url3.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '16 experiment 2', '16 Test', '16 hypothesis 1', 'http://www.url1.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '17 Experiment 2', '17 TEST', '17 hypothesis 2', 'http://www.url2.edu');
insert into experiment (id, name, description, hypothesis, url) values (nextval('hibernate_sequence'), '18 ExpPERment 3', '18 Test', '18 hypothesis 3', 'http://www.url3.edu');