alter table experiment drop constraint FKFAE9DBFD9477704D;
alter table experiment_run drop constraint FK7A9E7F49E2C93DCD;
alter table input_output_object drop constraint FK3CC95488E2C93DCD;
alter table protapp_inputs drop constraint FK10307C6EBCA925A7;
alter table protapp_inputs drop constraint FK10307C6EC71681E5;
alter table protapp_outputs drop constraint FK3F6C7DADC71681E5;
alter table protapp_outputs drop constraint FK3F6C7DAD2248C510;
alter table protocol drop constraint FKC50A8E989477704D;
alter table protocol_action drop constraint FK3CEBD1BDFFE924AD;
alter table protocol_action drop constraint FK3CEBD1BDE2C93DCD;
alter table protocol_application drop constraint FK901CE297084078D;
alter table protocol_application drop constraint FK901CE295EBC310C;
alter table simple_type_value drop constraint FK7D9430D91B7E2D84;
alter table simple_type_value drop constraint FK7D9430D92AAFD6E7;
alter table simple_type_value drop constraint FK7D9430D9F096EA07;
alter table simple_type_value drop constraint FK7D9430D9FFE924AD;
alter table simple_type_value drop constraint FK7D9430D9E2C93DCD;
alter table simple_type_value drop constraint FK7D9430D99477704D;
drop table experiment;
drop table experiment_run;
drop table input_output_object;
drop table person;
drop table protapp_inputs;
drop table protapp_outputs;
drop table protocol;
drop table protocol_action;
drop table protocol_application;
drop table simple_type_value;
drop sequence hibernate_sequence;
create table experiment (id int8 not null, creation_date timestamp not null, creator varchar(100) not null, modification_date timestamp not null, comments varchar(255), hypothesis varchar(255), name varchar(100) not null, url varchar(255), person_id int8, primary key (id));
create table experiment_run (id int8 not null, creation_date timestamp not null, creator varchar(100) not null, modification_date timestamp not null, comments varchar(255), name varchar(255) not null, experiment_id int8 not null, primary key (id));
create table input_output_object (id int8 not null, data_file_url varchar(255), name varchar(255) not null, experiment_id int8, primary key (id));
create table person (id int8 not null, contact_id varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), primary key (id));
create table protapp_inputs (protapp_id int8 not null, input_id int8 not null);
create table protapp_outputs (protapp_id int8 not null, output_id int8 not null);
create table protocol (id int8 not null, creation_date timestamp not null, creator varchar(100) not null, modification_date timestamp not null, description varchar(255), instrument varchar(255), name varchar(100) not null, software varchar(255), person_id int8, primary key (id));
create table protocol_action (id int8 not null, step_number int8 not null, protocol_id int8 not null, experiment_id int8, primary key (id));
create table protocol_application (id int8 not null, activity_date date not null, creation_date timestamp not null, creator varchar(100) not null, modification_date timestamp not null, comments varchar(255), name varchar(100) not null, prot_action_id int8 not null, experiment_run_id int8 not null, primary key (id));
create table simple_type_value (id int8 not null, name varchar(255), ontology_uri varchar(255), value varchar(255), value_type varchar(255), prot_application_id int8, protocol_id int8, person_id int8, dataobj_id int8, exprun_id int8, experiment_id int8, primary key (id));
create index experiment_name_idx on experiment (name);
create index experiment_comments_idx on experiment (comments);
alter table experiment add constraint FKFAE9DBFD9477704D foreign key (person_id) references person;
alter table experiment_run add constraint FK7A9E7F49E2C93DCD foreign key (experiment_id) references experiment;
alter table input_output_object add constraint FK3CC95488E2C93DCD foreign key (experiment_id) references experiment;
alter table protapp_inputs add constraint FK10307C6EBCA925A7 foreign key (input_id) references input_output_object;
alter table protapp_inputs add constraint FK10307C6EC71681E5 foreign key (protapp_id) references protocol_application;
alter table protapp_outputs add constraint FK3F6C7DADC71681E5 foreign key (protapp_id) references protocol_application;
alter table protapp_outputs add constraint FK3F6C7DAD2248C510 foreign key (output_id) references input_output_object;
create index protocol_desc_idx on protocol (description);
create index protocol_name_idx on protocol (name);
alter table protocol add constraint FKC50A8E989477704D foreign key (person_id) references person;
alter table protocol_action add constraint FK3CEBD1BDFFE924AD foreign key (protocol_id) references protocol;
alter table protocol_action add constraint FK3CEBD1BDE2C93DCD foreign key (experiment_id) references experiment;
alter table protocol_application add constraint FK901CE297084078D foreign key (prot_action_id) references protocol_action;
alter table protocol_application add constraint FK901CE295EBC310C foreign key (experiment_run_id) references experiment_run;
alter table simple_type_value add constraint FK7D9430D91B7E2D84 foreign key (dataobj_id) references input_output_object;
alter table simple_type_value add constraint FK7D9430D92AAFD6E7 foreign key (exprun_id) references experiment_run;
alter table simple_type_value add constraint FK7D9430D9F096EA07 foreign key (prot_application_id) references protocol_application;
alter table simple_type_value add constraint FK7D9430D9FFE924AD foreign key (protocol_id) references protocol;
alter table simple_type_value add constraint FK7D9430D9E2C93DCD foreign key (experiment_id) references experiment;
alter table simple_type_value add constraint FK7D9430D99477704D foreign key (person_id) references person;
create sequence hibernate_sequence start with 100;
