insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_q', 'Protocol q', 'Description for a', 'ExperimentRun');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qw', 'Protocol qw', 'Description for as', 'ExperimentRunOutput');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwe', 'Protocol qwe', 'Description for asd', 'SamplePrep');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwer', 'Protocol qwer', 'Description for asdf', 'ExperimentRun');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwert', 'Protocol qwert', 'Description for asdfg', 'ExperimentRunOutput');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwerty', 'Protocol qwerty', 'Description for asdfgh', 'SamplePrep');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwertyu', 'Protocol qwertyu', 'Description for asdfghj', 'ExperimentRun');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwertyui', 'Protocol qwertyui', 'Description for asdfghjk', 'ExperimentRunOutput');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwertyuio', 'Protocol qwertyuio', 'Description for asdfghjkl', 'SamplePrep');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwertyuiop', 'Protocol qwertyuiop', 'Description for asdfghjklc', 'ExperimentRun');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwertyuiopz', 'Protocol qwertyuiopz', 'Description for asdfghjklcv', 'ExperimentRunOutput');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_qwertyuiopzx', 'Protocol qwertyuiopzx', 'Description for asdfghjklcvb', 'SamplePrep');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_1', 'Protocol 1', 'This is a test protocol', 'ExperimentRun');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_2', 'Protocol 2', 'This is a test protocol', 'ExperimentRunOutput');
insert into protocol (id, lsid, name, description, type) values (nextval('hibernate_sequence'), 'Protocol_3', 'Protocol 3', 'This is a test protocol', 'SamplePrep');