function FileData_Pairs(x)
{
x.t("managing","experiments");
x.t("deleting","experiment");
x.t("experiments","working");
x.t("experiments","section");
x.t("working","experiments");
x.t("working","protexpress");
x.t("protexpress","creating");
x.t("editing","experiment");
x.t("new","experiment");
x.t("includes","following");
x.t("creating","new");
x.t("procedures","adding");
x.t("section","includes");
x.t("experiment","managing");
x.t("experiment","deleting");
x.t("experiment","editing");
x.t("following","procedures");
x.t("adding","experiment");
}
