function FileData_Pairs(x)
{
x.t("notes","repeat");
x.t("protocols","run");
x.t("deleting","experiment");
x.t("working","protexpress");
x.t("protexpress","editing");
x.t("delete","run");
x.t("editing","experiment");
x.t("details","repeating");
x.t("includes","following");
x.t("repeating","experiment");
x.t("add","protocols");
x.t("name","date");
x.t("edit","experiment");
x.t("run\u2019s","name");
x.t("section","includes");
x.t("experiment","editing");
x.t("experiment","run\u2019s");
x.t("experiment","run");
x.t("repeat","run");
x.t("date","performed");
x.t("topics","editing");
x.t("protocol","experiment");
x.t("run","deleting");
x.t("run","working");
x.t("run","delete");
x.t("run","editing");
x.t("run","details");
x.t("run","add");
x.t("run","edit");
x.t("run","section");
x.t("run","adding");
x.t("following","topics");
x.t("adding","protocol");
x.t("performed","notes");
}
