function FileData_Pairs(x)
{
x.t("home","page");
x.t("working","protexpress");
x.t("protexpress","getting");
x.t("resetting","password");
x.t("getting","started");
x.t("includes","following");
x.t("registering","users");
x.t("logging","resetting");
x.t("started","working");
x.t("started","getting");
x.t("started","section");
x.t("section","includes");
x.t("topics","registering");
x.t("users","logging");
x.t("following","topics");
x.t("using","home");
x.t("password","using");
}
