function FileData_Pairs(x)
{
x.t("protocols","during");
x.t("create","new");
x.t("create","process");
x.t("later","review");
x.t("working","protexpress");
x.t("protexpress","creating");
x.t("identify","experiment");
x.t("new","existing");
x.t("new","experiment");
x.t("add","new");
x.t("during","create");
x.t("creating","new");
x.t("review","experiment");
x.t("identifying","experiment");
x.t("existing","protocols");
x.t("process","later");
x.t("experiment","create");
x.t("experiment","working");
x.t("experiment","identify");
x.t("experiment","add");
x.t("experiment","creating");
x.t("experiment","save");
x.t("experiment","reviewing");
x.t("experiment","adding");
x.t("information","identifying");
x.t("save","information");
x.t("reviewing","experiment");
x.t("protocol","experiment");
x.t("adding","protocol");
}
