function FileData_Pairs(x)
{
x.t("protocols","bundled");
x.t("managing","experiments");
x.t("deleting","experiment");
x.t("instance","experiment");
x.t("action","sequence");
x.t("experiments","working");
x.t("working","protexpress");
x.t("working","experiment");
x.t("protexpress","managing");
x.t("editing","experiment");
x.t("applies","protocols");
x.t("section","contains");
x.t("given","experiment");
x.t("runs","working");
x.t("runs","experiment");
x.t("experiment","applies");
x.t("experiment","runs");
x.t("experiment","experiment");
x.t("experiment","run");
x.t("sequence","section");
x.t("bundled","protocol");
x.t("protocol","action");
x.t("topics","adding");
x.t("run","deleting");
x.t("run","instance");
x.t("run","editing");
x.t("run","given");
x.t("following","topics");
x.t("adding","experiment");
x.t("contains","following");
}
