function FileData_Pairs(x)
{
x.t("protocols","new");
x.t("topic","contains");
x.t("working","protexpress");
x.t("protexpress","creating");
x.t("new","experiment");
x.t("creating","new");
x.t("next","steps");
x.t("steps","adding");
x.t("identifying","experiment");
x.t("experiment","topic");
x.t("experiment","working");
x.t("experiment","identifying");
x.t("experiment","reviewing");
x.t("information","next");
x.t("reviewing","experiment");
x.t("adding","protocols");
x.t("contains","information");
}
