function FileData_Pairs(x)
{
x.t("protocols","experiments");
x.t("managing","experiments");
x.t("experiments","managing");
x.t("experiments","working");
x.t("experiments","section");
x.t("experiments","applying");
x.t("working","experiments");
x.t("working","protexpress");
x.t("working","experiment");
x.t("working","global");
x.t("protexpress","creating");
x.t("new","experiment");
x.t("includes","following");
x.t("creating","new");
x.t("section","includes");
x.t("experiment","managing");
x.t("experiment","runs");
x.t("global","inputs");
x.t("topics","working");
x.t("following","topics");
x.t("applying","protocols");
x.t("inputs","working");
}
