function FileData_Pairs(x)
{
x.t("searching","experiment");
x.t("managing","experiments");
x.t("deleting","experiment");
x.t("experiments","managing");
x.t("experiments","working");
x.t("experiments","section");
x.t("working","protexpress");
x.t("protexpress","managing");
x.t("editing","experiment");
x.t("editing","protocol");
x.t("includes","following");
x.t("procedures","searching");
x.t("section","includes");
x.t("experiment","deleting");
x.t("experiment","run");
x.t("experiment","adding");
x.t("application","editing");
x.t("protocol","application");
x.t("following","procedures");
x.t("run","editing");
x.t("run","adding");
x.t("adding","experiment");
x.t("adding","protocol");
}
