function FileData_Pairs(x)
{
x.t("protocols","managing");
x.t("protocols","working");
x.t("protocols","section");
x.t("managing","protocols");
x.t("deleting","protocol");
x.t("working","protexpress");
x.t("protexpress","creating");
x.t("editing","protocol");
x.t("new","experiment");
x.t("includes","following");
x.t("creating","new");
x.t("section","includes");
x.t("experiment","managing");
x.t("topics","adding");
x.t("protocol","deleting");
x.t("protocol","editing");
x.t("following","topics");
x.t("adding","protocol");
}
