function FileData_Pairs(x)
{
x.t("available","protocol");
x.t("managing","experiments");
x.t("deleting","global");
x.t("refers","inputs");
x.t("experiments","working");
x.t("working","protexpress");
x.t("working","global");
x.t("protexpress","managing");
x.t("protexpress","refers");
x.t("editing","global");
x.t("input","deleting");
x.t("input","editing");
x.t("section","contains");
x.t("material","inputs");
x.t("given","experiment");
x.t("runs","given");
x.t("experiment","protexpress");
x.t("experiment","runs");
x.t("data","material");
x.t("global","input");
x.t("global","inputs");
x.t("protocol","applications");
x.t("topics","adding");
x.t("applications","across");
x.t("following","topics");
x.t("across","experiment");
x.t("adding","global");
x.t("inputs","available");
x.t("inputs","working");
x.t("inputs","section");
x.t("inputs","global");
x.t("inputs","specify");
x.t("specify","data");
x.t("contains","following");
}
